sudo: required
services:
  - docker
env: 
  - TAG=2018-06-21
before_install:
  - cd worker
  - docker build -t rhodium/impactlab-worker:$TAG .
  - cd ../notebook
  - docker build -t rhodium/impactlab-notebook:$TAG .
script:
  - docker images rhodium/impactlab-notebook:$TAG
  - docker images rhodium/impactlab-worker:$TAG

#add push
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push rhodium/impactlab-worker:$TAG;
    docker push rhodium/impactlab-notebook:$TAG;
    fi
